### ISSUE TITLE
package.json dependencies

### ISSUE THREAD

**Issue by Flakke123** [travisneilson/Design-Code#13]
Hi,
iam complete new to github and even to html/css/sass/jade/everythingelse
pls forgive if i am totaly wrong here.

I downloaded the oldest version of design-code to start from beginning, if i try to setup it with
"npm install" i get

>0 info it worked if it ends with ok
>1 verbose cli [ 'F:\\nodejs\\node.exe',
>1 verbose cli   'F:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
>1 verbose cli   'install' ]
>2 info using npm@2.14.4
>3 info using node@v4.1.1
>4 verbose readDependencies loading dependencies from H:\webdesign\Design->Codev\package.json
>5 error install Couldn't read dependencies
>6 verbose stack Error: Failed to parse json
>6 verbose stack Unexpected token '�' at 12:1
>6 verbose stack � � "browser-sync": "^2.9.8",
>6 verbose stack ^
>6 verbose stack     at parseError (F:\nodejs\node_modules\npm\node_modules\read-package->json\read-json.js:379:11)
>6 verbose stack     at parseJson (F:\nodejs\node_modules\npm\node_modules\read-package->json\read-json.js:68:23)
>6 verbose stack     at F:\nodejs\node_modules\npm\node_modules\read-package-json\read->json.js:48:5
>6 verbose stack     at F:\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16
>6 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
>7 verbose cwd H:\webdesign\Design-Codev
>8 error Windows_NT 6.1.7601
>9 error argv "F:\\nodejs\\node.exe" "F:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
>10 error node v4.1.1
>11 error npm  v2.14.4
>12 error file H:\webdesign\Design-Codev\package.json
>13 error code EJSONPARSE
>14 error Failed to parse json
>14 error Unexpected token '�' at 12:1
>14 error � � "browser-sync": "^2.9.8",
>14 error ^
>15 error File: H:\webdesign\Design-Codev\package.json
>16 error Failed to parse package.json data.
>16 error package.json must be actual JSON, not just JavaScript.
>16 error
>16 error This is not a bug in npm.
>17 verbose exit [ 1, true ] 

npm show browser-sync gives me:

>  readmeFilename: 'README.md',
 > homepage: 'http://www.browsersync.io/',
 > keywords: [ 'browser sync', 'css', 'live reload', 'sync' ],
 > bugs: { url: 'https://github.com/Browsersync/browser-sync/issues' },
 > license: 'Apache-2.0',
 > version: '2.9.8',
>  bin: { 'browser-sync': 'bin/browser-sync.js' },
>  files: [ 'bin', 'index.js', 'lib' ],
>  engines: { node: '>= 0.8.0' },

Can maybe somebody tell me what i am doing wrong?
I am running a win7 64bit Computer..

**Comment by Flakke123** [comment]
Sorry, double post
