### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by rikiscripts** [travisneilson/Design-Code#9]
I tried installing browser-sync-jekyll using the package.json file included in this repo. It kept failing on me. I rewrote it and now it's installing like it should.

{
  "name": "browser-sync-jekyll",
  "version": "0.0.0",
  "description": "A starter project including full setup for Jekyll, GulpJS, SASS & BrowserSync",
  "main": "gulpfile.js",
  "devDependencies": {
    "browser-sync": "^2.8.2",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^2.3.1",
    "gulp-jade": "^1.1.0",
    "gulp-sass": "^2.0.4"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/shakyShane/jekyll-gulp-sass-browser-sync.git"
  },
  "keywords": [
    "jekyll",
    "gulp",
    "sass",
    "browsersync"
  ],
  "author": "Shane Osbourne",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/shakyShane/jekyll-gulp-sass-browser-sync/issues"
  },
  "homepage": "https://github.com/shakyShane/jekyll-gulp-sass-browser-sync"
}

**Comment by adamTrz** [comment]
i've had same issue - thanks a lot for correct dependencies list! :)

**Comment by Flakke123** [comment]
Hi,
i am complete new to github and even to html/css/sass/jade/everythingelse
pls forgive if i am totaly wrong here.

I downloaded the oldest version of design-code to start from beginning, if i try to setup it with
"npm install" i get:

0 info it worked if it ends with ok
1 verbose cli [ 'F:\nodejs\node.exe',
1 verbose cli 'F:\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'install' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose readDependencies loading dependencies from H:\webdesign\Design->Codev\package.json
5 error install Couldn't read dependencies
6 verbose stack Error: Failed to parse json
6 verbose stack Unexpected token '�' at 12:1
6 verbose stack � � "browser-sync": "^2.9.8",
6 verbose stack ^
6 verbose stack at parseError (F:\nodejs\node_modules\npm\node_modules\read-package->json\read-json.js:379:11)
6 verbose stack at parseJson (F:\nodejs\node_modules\npm\node_modules\read-package->json\read-json.js:68:23)
6 verbose stack at F:\nodejs\node_modules\npm\node_modules\read-package-json\read->json.js:48:5
6 verbose stack at F:\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16
6 verbose stack at FSReqWrap.readFileAfterClose as oncomplete
7 verbose cwd H:\webdesign\Design-Codev
8 error Windows_NT 6.1.7601
9 error argv "F:\nodejs\node.exe" "F:\nodejs\node_modules\npm\bin\npm-cli.js" "install"
10 error node v4.1.1
11 error npm v2.14.4
12 error file H:\webdesign\Design-Codev\package.json
13 error code EJSONPARSE
14 error Failed to parse json
14 error Unexpected token '�' at 12:1
14 error � � "browser-sync": "^2.9.8",
14 error ^
15 error File: H:\webdesign\Design-Codev\package.json
16 error Failed to parse package.json data.
16 error package.json must be actual JSON, not just JavaScript.
16 error
16 error This is not a bug in npm.
17 verbose exit [ 1, true ]

**npm** show browser-sync gives me:

readmeFilename: 'README.md',
homepage: 'http://www.browsersync.io/',
keywords: [ 'browser sync', 'css', 'live reload', 'sync' ],
bugs: { url: 'https://github.com/Browsersync/browser-sync/issues' },
license: 'Apache-2.0',
version: '2.9.8',
bin: { 'browser-sync': 'bin/browser-sync.js' },
files: [ 'bin', 'index.js', 'lib' ],
engines: { node: '>= 0.8.0' },


**Can** maybe somebody tell me what i am doing wrong?
I am running a win7 64bit Computer..

**Comment by onedaylove** [comment]
Did you cd into the folder that your package.json file is located using cmd prompt? You know..cd /path/to/folder/in/windows/

**Comment by Flakke123** [comment]
Yes. Like this:
http://www.pic-upload.de/view-28466815/npminstalfehler.jpg.html

I downloaded the ZIP cd into the "main" directory (the one with with package.json) and tried to "npm install", did i forget something?

here are my changes to the package.json:
> "author": "Shane Osbourne",
>  "license": "ISC",
>  "devDependencies": {
>  "browser-sync": "^2.9.8",
>    "gulp": "^3.9.0",
>   "gulp-autoprefixer": "^3.0.2",
>   "gulp-jade": "^1.1.0",
>   "gulp-sass": "^2.0.4"

**Comment by onedaylove** [comment]
The only changes I made to the package.json file were the version numbers for the dependencies. The packages were outdated in the original file. Those should install just fine. I'm gonna test it out for myself and see if I can figure out what might be the problem. Hang tight alright.

**Comment by onedaylove** [comment]
Is there a way I could see the package.json file you're using right now? If possible, could I see a screenshot of the file opened in whatever code editor you're using?

**Comment by Flakke123** [comment]
I did the same, i changed the version numbers to one that i have installed (or i am thinking i have installed)

Here it is:
https://spideroak.com/browse/share/Flakke123/1234567/SpiderOak%20Hive/

**Comment by onedaylove** [comment]
I just did a test with all the code I provided above and it installed just fine. Here...Download this package.json file. Don't modify a thing inside the file. Replace the package.json file you have in the folder with this one and try the install again. It should work.

https://www.dropbox.com/s/9ssa68gb41tutd9/package.json?dl=0

**Comment by onedaylove** [comment]
Also..Delete the node_modules folder you already have in the folder.

**Comment by onedaylove** [comment]
As you can see from this output everything on the package.json file installed properly for me:

Last login: Fri Oct  2 02:56:48 on ttys000
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
# ryanx30                                                                       
$ cd Desktop/untitled\ folder/
# untitled folder                                                               
$ sudo npm install
Password:
npm WARN package.json browser-sync-jekyll@0.0.0 No README data
 
> spawn-sync@1.0.13 postinstall /Users/ryanx30/Desktop/untitled folder/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

 
> node-sass@3.3.3 install /Users/ryanx30/Desktop/untitled folder/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/ryanx30/Desktop/untitled folder/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node

> bufferutil@1.2.1 install /Users/ryanx30/Desktop/untitled folder/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /Users/ryanx30/Desktop/untitled folder/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> bufferutil@1.2.1 install /Users/ryanx30/Desktop/untitled folder/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /Users/ryanx30/Desktop/untitled folder/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> node-sass@3.3.3 postinstall /Users/ryanx30/Desktop/untitled folder/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /Users/ryanx30/Desktop/untitled folder/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.

> fsevents@1.0.1 install /Users/ryanx30/Desktop/untitled folder/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/ryanx30/Desktop/untitled folder/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote
gulp-jade@1.1.0 node_modules/gulp-jade
├── through2@2.0.0 (xtend@4.0.0, readable-stream@2.0.2)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, object-assign@3.0.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, replace-ext@0.0.1, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.1, lodash.template@3.6.2, dateformat@1.0.11, multipipe@0.1.2)
└── jade@1.11.0 (commander@2.6.0, character-parser@1.2.1, void-elements@2.0.1, mkdirp@0.5.1, jstransformer@0.0.2, constantinople@3.0.2, with@4.0.3, clean-css@3.4.5, transformers@2.1.0, uglify-js@2.4.24)

gulp@3.9.0 node_modules/gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── semver@4.3.6
├── tildify@1.1.1 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── gulp-util@3.0.6 (array-uniq@1.0.2, array-differ@1.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, replace-ext@0.0.1, vinyl@0.5.3, multipipe@0.1.2, through2@2.0.0, lodash.template@3.6.2, dateformat@1.0.11)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, defaults@1.0.2, through2@0.6.5, strip-bom@1.0.0, vinyl@0.4.6, mkdirp@0.5.1, glob-watcher@0.0.6, glob-stream@3.1.18)
└── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.3.0)

gulp-autoprefixer@2.3.1 node_modules/gulp-autoprefixer
├── object-assign@2.1.1
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── postcss@4.1.16 (js-base64@2.1.9, es6-promise@2.3.0, source-map@0.4.4)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, object-assign@3.0.0, beeper@1.1.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.1, through2@2.0.0, lodash.template@3.6.2, dateformat@1.0.11, multipipe@0.1.2)
└── autoprefixer-core@5.2.1 (browserslist@0.4.0, num2fraction@1.2.2, caniuse-db@1.0.30000331)

gulp-sass@2.0.4 node_modules/gulp-sass
├── object-assign@2.1.1
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── gulp-util@3.0.6 (array-uniq@1.0.2, array-differ@1.0.0, beeper@1.1.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.1, lodash.template@3.6.2, dateformat@1.0.11, through2@2.0.0, multipipe@0.1.2)
└── node-sass@3.3.3 (get-stdin@4.0.1, async-foreach@0.1.3, nan@2.0.9, mkdirp@0.5.1, gaze@0.5.1, glob@5.0.15, npmconf@2.1.2, meow@3.3.0, chalk@1.1.1, cross-spawn@2.0.0, node-gyp@3.0.3, request@2.64.0, sass-graph@2.0.1)

browser-sync@2.9.8 node_modules/browser-sync
├── async-each-series@0.1.1
├── longest@1.0.1
├── ucfirst@1.0.0
├── emitter-steward@1.0.0
├── dev-ip@1.0.1
├── immutable@3.7.5
├── ua-parser-js@0.7.9
├── opn@3.0.2 (object-assign@3.0.0)
├── query-string@2.4.1 (strict-uri-encode@1.0.2)
├── pad-left@2.0.0 (repeat-string@1.5.2)
├── portscanner@1.0.0 (async@0.1.15)
├── easy-extender@2.3.1 (lodash@2.4.2)
├── lodash@3.10.1
├── browser-sync-client@2.3.1 (etag@1.7.0, fresh@0.3.0)
├── resp-modifier@5.0.2 (debug@2.2.0, minimatch@2.0.10)
├── connect@3.4.0 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.2.0, finalhandler@0.4.0)
├── meow@3.3.0 (object-assign@3.0.0, minimist@1.2.0, camelcase-keys@1.0.0, indent-string@1.2.2)
├── eazy-logger@2.1.2 (opt-merger@1.1.0, tfunk@3.0.1)
├── serve-static@1.10.0 (escape-html@1.0.2, parseurl@1.3.0, send@0.13.0)
├── serve-index@1.7.2 (escape-html@1.0.2, parseurl@1.3.0, batch@0.5.2, http-errors@1.3.1, debug@2.2.0, mime-types@2.1.7, accepts@1.2.13)
├── localtunnel@1.7.0 (debug@0.7.4, openurl@1.1.0, request@2.11.4, yargs@3.15.0)
├── foxy@11.1.3 (cookie@0.1.5, http-proxy@1.11.2, resp-modifier@4.0.4, lodash.merge@3.3.2)
├── anymatch@1.3.0 (arrify@1.0.0, micromatch@2.2.0)
├── browser-sync-ui@0.5.16 (connect-history-api-fallback@0.0.5, stream-throttle@0.1.3, weinre@2.0.0-pre-I0Z7U9OV)
├── socket.io@1.3.7 (debug@2.1.0, has-binary-data@0.1.3, socket.io-parser@2.2.4, socket.io-adapter@0.3.1, engine.io@1.5.4, socket.io-client@1.3.7)
└── chokidar@1.2.0 (arrify@1.0.0, path-is-absolute@1.0.0, async-each@0.1.6, glob-parent@2.0.0, is-glob@2.0.1, is-binary-path@1.0.1, readdirp@2.0.0, lodash.flatten@3.0.2, fsevents@1.0.1)
# untitled folder                                                               
$

**Comment by Flakke123** [comment]
It´s working now, thank you very much so far!

I found about 100 "node_modules" folders in c:\Users\username\appData\roaming\npm\ and all the subfolders.. which one are you talking about?

In my "working-directory" (Design-Code) isn´t one.

**Comment by onedaylove** [comment]
Well ok then. You're good to go.

**Comment by brunoalv-s** [comment]
> I just did a test with all the code I provided above and it installed just fine. Here...Download this package.json file. Don't modify a thing inside the file. Replace the package.json file you have in the folder with this one and try the install again. It should work.
>
> https://www.dropbox.com/s/9ssa68gb41tutd9/package.json?dl=0

@onedaylove do you could share this package.json with me?

Link is broken here. :(

**Comment by onedaylove** [comment]
@brunoalv-s 

Take this and make yourself a package.json file for your project:

{
"name": "browser-sync-jekyll",
"version": "0.0.0",
"description": "A starter project including full setup for Jekyll, GulpJS, SASS & BrowserSync",
"main": "gulpfile.js",
"devDependencies": {
"browser-sync": "^2.11.1",
"gulp": "^3.9.1",
"gulp-autoprefixer": "^3.1.0",
"gulp-jade": "^1.1.0",
"gulp-sass": "^2.2.0"
},
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1"
},
"repository": {
"type": "git",
"url": "https://github.com/shakyShane/jekyll-gulp-sass-browser-sync.git"
},
"keywords": [
"jekyll",
"gulp",
"sass",
"browsersync"
],
"author": "Shane Osbourne",
"license": "ISC",
"bugs": {
"url": "https://github.com/shakyShane/jekyll-gulp-sass-browser-sync/issues"
},
"homepage": "https://github.com/shakyShane/jekyll-gulp-sass-browser-sync"
}

**Comment by brunoalv-s** [comment]
Thanks for the fast answer.

I did what you suggested and got run npm install, I had to write it all for myself. Thank you again.

PS: Sorry for my english. :(

**Comment by onedaylove** [comment]
@brunoalv-s You could have just copy and pasted my last response onto a package.json file and put it into the root of your project folder. Would have saved you the time, but whatever works right.

**Comment by brunoalv-s** [comment]
@onedaylove  That's what I did. But it did not work, then I copied manually and finally worked. I will never understand. =/

**Comment by onedaylove** [comment]
@brunoalv-s Here's a copy of the file: https://www.dropbox.com/s/9ssa68gb41tutd9/package.json?dl=0

I'll try to not delete this one.

**Comment by brunoalv-s** [comment]
Thank you so much for your help @onedaylove 

Forgive me thank so late. Thanks again.

**Comment by frog79** [comment]
and it got deleted again! lol , why is this not committed to the code, do you have any idea how many thousands of people are still following travis? and are learning, this should be updated properly.

**Comment by onedaylove** [comment]
@frog79 

This is the most updated. Why don't you fork Travis' project and update the package.json file with this.
{
"name": "browser-sync-jekyll",
"version": "0.0.0",
"description": "A starter project including full setup for Jekyll, GulpJS, SASS & BrowserSync",
"main": "gulpfile.js",
"devDependencies": {
"browser-sync": "^2.11.2",
"gulp": "^3.9.1",
"gulp-autoprefixer": "^3.1.0",
"gulp-jade": "^1.1.0",
"gulp-sass": "^2.2.0"
},
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1"
},
"repository": {
"type": "git",
"url": "https://github.com/shakyShane/jekyll-gulp-sass-browser-sync.git"
},
"keywords": [
"jekyll",
"gulp",
"sass",
"browsersync"
],
"author": "Shane Osbourne",
"license": "ISC",
"bugs": {
"url": "https://github.com/shakyShane/jekyll-gulp-sass-browser-sync/issues"
},
"homepage": "https://github.com/shakyShane/jekyll-gulp-sass-browser-sync"
}

**Comment by jhonix22** [comment]
This line `` "test": "echo "Error: no test specified" && exit 1"`` caused a syntax error on my side.
Deleting the double quotes wrapped around the ``Error: no test specified`` fixed the error. 
It will look like this ``"test": "echo Error: no test specified && exit 1"``. Hope that helps :)

**Comment by michenus** [comment]
If command console "**npm install**" causes the error:
`
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! file D:\Sites\GulpSites\Design-Code-master\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token ' ' at 12:1
npm ERR!     "browser-sync": "^2.8.0",
npm ERR! ^
npm ERR! File: D:\Sites\GulpSites\Design-Code-master\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Sites\GulpSites\Design-Code-master\npm-debug.log
`

[http://prntscr.com/diss7o](url) -> there is a mistake.
**Need to convert spaces to tabs.** 
And the command "npm install" will work
